source 'https://rubygems.org'

gem 'actionpack', '~> 5.1.4'
gem 'activerecord', '~> 5.1.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets

gem "trailblazer" # ,       path: "../../../trailblazer"
gem "trailblazer-rails", path: "../../../trailblazer-rails"

group :test do
  gem "minitest-rails-capybara"
end

gem "cells-erb"
gem "cells-rails"
gem "trailblazer-cells"

gem "minitest", '~> 5.10', '!= 5.10.2'

gem "reform-rails"
