source "https://rubygems.org"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "actionpack", "~> 5.1.4"
gem "activerecord", "~> 5.1.4"
# Use sqlite3 as the database for Active Record
gem "sqlite3"

eval_gemfile("../../Gemfile")

group :test do
  gem "minitest-rails-capybara"
end

gem "minitest-line"

gem "byebug"
