source 'https://rubygems.org'

gem 'actionpack', '~> 6.0.0'
gem 'activerecord', '~> 6.0.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem "trailblazer"
gem "trailblazer-rails", path: "../../../trailblazer-rails"

group :test do
  gem "minitest-capybara"
end

gem "cells-erb"
gem "cells-rails"
gem "trailblazer-cells"

gem "reform-rails"

gem "byebug"
