inherit_from:
  - https://raw.githubusercontent.com/trailblazer/meta/master/rubocop.yml
  - .rubocop_todo.yml

Style/ClassCheck:
  Exclude:
    - 'lib/trailblazer/rails/cell.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/trailblazer/rails/controller.rb'

Bundler/DuplicatedGem:
  Enabled: false
