source "https://rubygems.org"

gem "actionpack", "~> 4.2.10"
gem "activerecord", "~> 4.2.10"
# Use sqlite3 as the database for Active Record
gem "sqlite3"
# Use SCSS for stylesheets

gem "trailblazer" # ,       path: "../../../trailblazer"
gem "trailblazer-rails", path: "../../../trailblazer-rails"

group :test do
  gem "minitest-rails-capybara"
end

gem "cells-erb"
gem "cells-rails"
gem "trailblazer-cells"

gem "minitest-line"

gem "reform-rails"
