source "https://rubygems.org"

gem "actionpack", "~> 4.2.10"
gem "activerecord", "~> 4.2.10"
# Use sqlite3 as the database for Active Record
gem "sqlite3"
# Use SCSS for stylesheets

eval_gemfile("../../Gemfile")

group :test do
  gem "minitest-rails-capybara"
end

gem "minitest-line"
