source 'https://rubygems.org'

gem 'rails', '3.2.22.2'

gem 'sqlite3'

gem "trailblazer-rails", path: "../../../trailblazer-rails"
gem "trailblazer"#,       path: "../../../trailblazer"

gem "trailblazer-cells"
gem "cells-rails"
gem "cells-erb"

gem "minitest-line"

gem "reform-rails"
