source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem "trailblazer"
gem "trailblazer-rails", path: "../../../trailblazer-rails"

group :test do
  gem "minitest"
  gem "minitest-capybara"
end

gem "cells-erb"
gem "cells-rails"
gem "trailblazer-cells"

gem "reform-rails"

gem "byebug"
