source "https://rubygems.org"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "actionpack", "~> 5.0.7"
gem "activerecord", "~> 5.0.7"
# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.3", "< 1.4"

eval_gemfile("../../Gemfile")

group :test do
  gem "minitest-rails-capybara"
end

gem "minitest-line"

gem "byebug"
